name: Performance Monitoring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Serve built files
      run: |
        npm install -g serve
        serve -s dist -p 3000 &
        sleep 5
      
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Bundle Analysis
      run: |
        npm install -g webpack-bundle-analyzer
        npx vite-bundle-analyzer dist --analyzer-mode json --report-filename bundle-report.json || true

    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-results
        path: |
          .lighthouseci/
          bundle-report.json
        retention-days: 30

  bundle-size:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build and analyze bundle
      run: |
        npm run build
        echo "## Bundle Size Report" >> $GITHUB_STEP_SUMMARY
        echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------|" >> $GITHUB_STEP_SUMMARY
        find dist -name "*.js" -o -name "*.css" | while read file; do
          size=$(du -h "$file" | cut -f1)
          filename=$(basename "$file")
          echo "| $filename | $size |" >> $GITHUB_STEP_SUMMARY
        done

    - name: Check bundle size limits
      run: |
        # JSファイルの合計サイズをチェック (500KB制限)
        total_js_size=$(find dist -name "*.js" -exec du -b {} + | awk '{sum+=$1} END {print sum}')
        if [ "$total_js_size" -gt 512000 ]; then
          echo "❌ JavaScript bundle size ($total_js_size bytes) exceeds 500KB limit"
          exit 1
        else
          echo "✅ JavaScript bundle size ($total_js_size bytes) is within limits"
        fi